### PR TITLE
Release 1.10.2

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ngam** [comment]
Looks good, thanks a lot @hmaarrfk for all your work on this!!

**Comment by ngam** [comment]
@hmaarrfk, not sure if there is a list of potential small improvements somewhere, but one thing we could potentially do is to unify the hashes. For example: 

```
  pytorch                                     1.10.1  cuda112py39h4de5995_0   conda-forge/linux-64      637 MB
  pytorch-gpu                                 1.10.1  cuda112py39h0bbbad9_0   conda-forge/linux-64       10 KB
```

I think it would maybe make sense to have these hashes be the same. I have no idea how/why this is not working based on meta, and it really isn't a big deal at all. Just a note of this here for now.

**Comment by hmaarrfk** [comment]
The hashes really rely on the list of dependencies. They are meant to be unique as dependencies change. You won't be able to patch them between cpu/gpu builds, and they aren't expected to match either.

**Comment by hmaarrfk** [comment]
[linux_64_c_compiler_version_log.zip](https://github.com/conda-forge/pytorch-cpu-feedstock/files/7966095/linux_64_c_compiler_version_log.zip)

@isuruf could you upload builds from the channel
https://anaconda.org/mark.harfouche/repo

label `cefp03`

CPU packages are building on CIs.

**Pull request merged**
