### PR TITLE
migrate to libprotobuf321

### PR DESCRIPTION
**Pull request by ngam**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
Maybe this file needs to be updated for OSX https://github.com/ngam/pytorch-cpu-feedstock/blob/libprotobuf/recipe/conda_build_config.yaml#L1

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by h-vetinari** [comment]
> Maybe this file needs to be updated for OSX https://github.com/ngam/pytorch-cpu-feedstock/blob/libprotobuf/recipe/conda_build_config.yaml#L1

That's there since https://github.com/conda-forge/pytorch-cpu-feedstock/commit/8e4ce1926d0cb6f0a95161d6599b895c3e5b1586. Ideally things should be fine if `MACOSX_DEPLOYMENT_TARGET` is not set, but 12.3 might not be able to compile for that target anymore.

I remember looking this up [once](https://github.com/conda-forge/conda-forge.github.io/issues/1798#issuecomment-1191377086)... Based on https://developer.apple.com/support/xcode/, it looks we need to stay with xcode<14, otherwise we don't have support for deployment targets <11 anymore (or add `__osx >=11`)

**Comment by hmaarrfk** [comment]
i think lief-dev is now old, and just lief 11.2 or something is out.

**Comment by hmaarrfk** [comment]
This needs: https://github.com/asmjit/asmjit/commit/c59847629d3a19da4d10f0be4ac33b43fc4a100f

**Comment by hmaarrfk** [comment]
maybe we should just downgrade the c ompiler.

**Comment by hmaarrfk** [comment]
compilers often increase severity on "bad practices" with newer versions. I've linked to the patch that addressed this.

It seems that for now, the easiest might be to downgrade the compiler

**Comment by h-vetinari** [comment]
> @hmaarrfk no rush on this. I think it would be reasonable to get it done when the next minor pytorch is out

Not making this makes pytorch and all dependent packages run into the same kind of solvability problems we were discussing for tf. So while we shouldn't perhaps be rushing unduly, we should definitely get this in as soon as time allows, and not wait for the next version.

**Review by h-vetinari — APPROVED** [review]

**Comment by hmaarrfk** [comment]
i don't have the compute power right now to build. so if you can build that would be great!

**Comment by hmaarrfk** [comment]
i think many downstream packages are still stuck on older cuda. I owuld like to keep the 11 series.

**Comment by hmaarrfk** [comment]
ok i've started with 10.2. historically it has 3 hours per build. So maybe 24 hours.

**Comment by hmaarrfk** [comment]
sorry about the delay, tbh, i had the builds, but ultimately more pressing fires happened :/ this is the main issue with CFEP03, it centralizes too much "power"

**Comment by hmaarrfk** [comment]
I'll wait for your builds, it makes the copying process more streamlined.

**Comment by hmaarrfk** [comment]
thanks!

**Pull request merged**
