### PR TITLE
BUG: Add missing dep on setuptools for python>=3.12

### PR DESCRIPTION
**Pull request by carterbox**
https://github.com/pytorch/pytorch/commit/d6368985af9f670db43b9a644f878d4e57e67b6b Closes https://github.com/conda-forge/pytorch-cpu-feedstock/issues/274

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by carterbox** [comment]
@conda-forge-admin, please rerender

**Comment by hmaarrfk** [comment]
Are we OK with a full new upload? if so i'll just merge and we can let this minor change happen on the main branch.

**Comment by hmaarrfk** [comment]
can you also verbally confirm that you've gone through the other dependency and refreshed their requirements?

**Comment by carterbox** [comment]
https://github.com/pytorch/pytorch/blob/v2.4.1/setup.py#L1123-L1136

I confirm that I have compared the python requirements listed in this recipe with those declared in the link above (the depdendencies declared in the setup.py file for release 2.4.1). The conda recipe does not include the extras for optree and opt-einsum.

**Comment by hmaarrfk** [comment]
> The conda recipe does not include the extras for optree and opt-einsum.

ok we can do this a "future" fix.

**Pull request merged**
