### PR TITLE
[WIP] Cuda12 rebuild again

### PR DESCRIPTION
**Pull request by RaulPPelaez**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

There were some conflicts in my previous PR #181 , I think I was able to solve them.

### CODE REVIEW

**Comment by RaulPPelaez** [comment]
OSX builds run into this error https://github.com/pytorch/pytorch/issues/99035
Now trying to silence it with `-Wno-unused-command-line-argument`

**Comment by RaulPPelaez** [comment]
Silencing causes this error in CMake:
```
-- Performing Test COMPILER_SUPPORTS_AVX512 - Failed
  CMake Error at third_party/fbgemm/CMakeLists.txt:76 (message):
    A compiler with AVX512 support is required.


  -- Configuring incomplete, errors occurred!
  error: subprocess-exited-with-error
  
```

**Comment by jakirkham** [comment]
Interesting wonder why AVX512 support is a hard requirement? Not all CPUs have those instructions

**Comment by Tobias-Fischer** [comment]
I think we should just set `USE_FBGEMM=OFF` for osx.

The check for avx512 is different in pytorch where they decide whether to build fbgemm (https://github.com/pytorch/pytorch/blob/71632d4d24616ddad6685814aae4ae54c981c0d2/cmake/MiscCheck.cmake#L43-L83 - this succeeds) and within fbgemm itself (https://github.com/pytorch/FBGEMM/blob/d43717ad9f62c30a89a31d537303e7d5970c1018/CMakeLists.txt#L111-L122 - fails).

**Comment by RaulPPelaez** [comment]
@conda-forge-admin, please rerender

**Comment by RaulPPelaez** [comment]
The lingering issues are:
- In some OSX build succeeds, test fail with this error:
```shell
Traceback (most recent call last):
  File "backends/xeon/test_launch.py", line 65, in <module>
    run_tests()
  File "/Users/runner/miniforge3/conda-bld/pytorch-recipe_1693911031252/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 765, in run_tests
    from xmlrunner.result import _XMLTestResult  # type: ignore[import]
ModuleNotFoundError: No module named 'xmlrunner.result'
FINISHED PRINTING LOG FILE of backends/xeon/test_launch (/Users/runner/miniforge3/conda-bld/pytorch-recipe_1693911031252/test_tmp/test/test-reports/backends-xeon-test_launch_kar0386k.log)

backends/xeon/test_launch failed!
Traceback (most recent call last):
  File "./test/run_test.py", line 1394, in <module>
    main()
  File "./test/run_test.py", line 1352, in main
    raise RuntimeError(
RuntimeError: backends/xeon/test_launch failed!

```
But the xmlrunner package is being installed, and this error is not present in many other osx builds.
- In some cpu only linux builds build succeeds, but test fails to install the env with this error:
```shell

with channels:

The reported errors are:
- Encountered problems while solving:
-   - package pytorch-2.0.0-cpu_generic_py38h1a61d8b_1 requires mkl >=2022.2.1,<2023.0a0, but none of the providers can be installed
- 
```
weird because the mkl package is installed during build just fine.

**Comment by jakirkham** [comment]
Now that PR ( https://github.com/conda-forge/pytorch-cpu-feedstock/pull/195 ) is in, should we close this?

**Pull request closed without merging**
