### PR TITLE
1.13.0

### PR DESCRIPTION
**Pull request by ngam**
summary:
- [x] py311
- [x] drop cuda <11.2
- [x] test again new magma https://github.com/conda-forge/magma-feedstock/pull/20

--

Closes #145 
Closes #138 
Closes #146 
Closes #150 

--

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by carterbox** [comment]
Try adding `-DUSE_NUMA=OFF -DUSE_ITT=OFF` To the `CMAKE_ARGS` variable?

```
2022-10-31T01:02:14.3032505Z   -- Could NOT find Numa (missing: Numa_INCLUDE_DIR Numa_LIBRARIES)
2022-10-31T01:02:14.3037789Z   CMake Warning at cmake/Dependencies.cmake:889 (message):
2022-10-31T01:02:14.3044564Z     Not compiling with NUMA.  Suppress this warning with -DUSE_NUMA=OFF
2022-10-31T01:02:14.3050825Z   Call Stack (most recent call first):
2022-10-31T01:02:14.3057331Z     CMakeLists.txt:722 (include)
2022-10-31T01:02:14.3063835Z 
2022-10-31T01:02:14.3073925Z 
2022-10-31T01:02:14.3132132Z   CMake Warning at cmake/Dependencies.cmake:968 (message):
2022-10-31T01:02:14.3143094Z     Not compiling with ITT.  Suppress this warning with -DUSE_ITT=OFF
2022-10-31T01:02:14.3153095Z   Call Stack (most recent call first):
2022-10-31T01:02:14.3163417Z     CMakeLists.txt:722 (include)
2022-10-31T01:02:14.3173746Z 
2022-10-31T01:02:14.3183236Z 
2022-10-31T01:02:14.3193719Z   CMake Error at cmake/public/utils.cmake:188 (set):
2022-10-31T01:02:14.3203264Z     set given invalid arguments for CACHE mode.
2022-10-31T01:02:14.3214050Z   Call Stack (most recent call first):
2022-10-31T01:02:14.3224179Z     cmake/Dependencies.cmake:970 (caffe2_update_option)
2022-10-31T01:02:14.3234124Z     CMakeLists.txt:722 (include)
2022-10-31T01:02:14.3243872Z 
2022-10-31T01:02:14.3255322Z 
```
The first suppresses this warning and the second will avoid the code path causing this error.

**Comment by carterbox** [comment]
Appending these args to CMAKE_ARGS didn't actually add the args to the CMake cache because the warnings from CMake are still there. There must be a different way to do it.

**Comment by hmaarrfk** [comment]
Few questions:

1. do you want to wait for magma 2.6.2? 
2. I don't think we should "accidentally" drop other cudas as part of this, nor do I think we should attempt to revive the discussion here. If you want to accelerate things, then lets discuss in the other PR. Otherwise, lets wait for Nov 21st for any stragglers. I know this "sucks" but we have to ensure that we are transparent, otherwise, its somewhat confusing to others what the support matrix is. To me, it is a pretty good incentive to "drop 11.2". We don't want to maintain it. So you won't get any new features.

**Comment by hmaarrfk** [comment]
ok, lets wait a bit.

**Comment by hmaarrfk** [comment]
hmm, sorry for conflict. lets see if the CIs are working and we can upload the packages you already built.

**Comment by hmaarrfk** [comment]
ok, maybe you can rebase then? you can delete the commit i just did.

**Comment by hmaarrfk** [comment]
Thanks! Very much appreciated!

**Pull request merged**
