### PR TITLE
1.6.0 again

### PR DESCRIPTION
**Pull request by hmaarrfk**
* I had to merge build and host to get around: https://github.com/pytorch/pytorch/issues/11636
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
https://github.com/pytorch/pytorch/issues/5217

**Comment by hmaarrfk** [comment]
@conda-forge/llvmdev do you know how I can get osx to find LLVM FileCheck?:
```
  -- Failed to find LLVM FileCheck
```

**Comment by hadim** [comment]
> @conda-forge/llvmdev do you know how I can get osx to find LLVM FileCheck?:

Did you manage to get the build to work for Linux (with and without cuda support)? (I cannot see the logs anymore)

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by isuruf** [comment]
close in favour of #21?

**Pull request closed without merging**
