### PR TITLE
Testing GH Actions instead of Azure

### PR DESCRIPTION
**Pull request by hadim**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Can you skip most builds? maybe

```
skip: true  # [py!=310]
```

**Comment by hadim** [comment]
@hmaarrfk here is a test using GH Actions instead of Azure. As suggested (https://github.com/conda-forge/pytorch-cpu-feedstock/issues/108#issuecomment-1356355748), I had to comment out the line blocking GH Actions for conda-forge in `conda-smithy` during `regenerate`.

I guess the goal here is to check how long the CI takes. I don't think it's available for free, but updating the current CI to larger runners is supposed to one-click-away from a `conda-forge` GH org admin.

**Comment by hmaarrfk** [comment]
I understand the test. But we don't need to build all of these just to test. At this stage, we can limit the build matrix until most things are debugged.

**Comment by hadim** [comment]
`skip: true  # [py!=310]` generates no CI.

**Comment by hmaarrfk** [comment]
i think maybe the syntax changed and they don't want us to use 310 anymore

```
skip: true  # [py38]
skip: true  # [py39]
skip: true  # [py311
```

**Comment by hmaarrfk** [comment]
I guess lets see how far the linux builds go

**Comment by hadim** [comment]
The regular GH runners seems similar to the Azure ones (2 CPUs, 6h limit).

I guess the build time will be similar.

Only large runners will make a difference: https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners#machine-specs-for-larger-runners

But those are not free even for public repos. And it sounds like paying for it (even for quick testing) will require a lot of bureaucracy xD

**Comment by hadim** [comment]
> Are you aware of larger runners for osx btw?

For now, it seems to be only for linux and windows. I guess it's a matter of time before osx is proposed.

**Comment by hmaarrfk** [comment]
Personally, if we are going to pay money from a limited pool to get this built on linux, i would appreciate some help in unbundling things, so that we only have to use the larger runners once, for the GPU builds.

**Pull request closed without merging**
