### PR TITLE
Add lief dev

### PR DESCRIPTION
**Pull request by hmaarrfk**
I'm not sure if this should help the osx builds.

It does speed things up for tensorflow. maybe it can speed things up for OSX too?

Normal build times are at about 4-5 hours now
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
I don't think we should merge this in now, but we should consider this in the next rebuild.

**Comment by hmaarrfk** [comment]
@xhochy is it reasonable to expect the following speedup from lief dev?
On Master:
image

On this branch:
image


5.5 Hours gets close to timing out often.

**Comment by rgommers** [comment]
We've certainly seen a regression of that size before due to lief version used by conda-build when building the conda packages for the pytorch channel, so it doesn't seem impossible.

**Comment by xhochy** [comment]
Yes, the speedup is reasonable. In the case of `tensorflow` and `ghc`, `lief` took longer on osx than the actual build. In the currently released version, there is a section of code that is quadratic in the number of symbols. The newer version is linear.

**Comment by xhochy** [comment]
FYI, the GCC error in the build logs is the exact same we see in `tensorflow` when switching to GCC 10:

```
[2/3010] Building NVCC (Device) object third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir/nccl/gloo_cuda_generated_nccl.cu.o
  FAILED: third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir/nccl/gloo_cuda_generated_nccl.cu.o /home/conda/feedstock_root/build_artifacts/pytorch-recipe_1645486153516/work/build/third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir/nccl/gloo_cuda_generated_nccl.cu.o
  cd /home/conda/feedstock_root/build_artifacts/pytorch-recipe_1645486153516/work/build/third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir/nccl && /home/conda/feedstock_root/build_artifacts/pytorch-recipe_1645486153516/_build_env/bin/cmake -E make_directory /home/conda/feedstock_root/build_artifacts/pytorch-recipe_1645486153516/work/build/third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir/nccl/. && /home/conda/feedstock_root/build_artifacts/pytorch-recipe_1645486153516/_build_env/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=Release -D generated_file:STRING=/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1645486153516/work/build/third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir/nccl/./gloo_cuda_generated_nccl.cu.o -D generated_cubin_file:STRING=/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1645486153516/work/build/third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir/nccl/./gloo_cuda_generated_nccl.cu.o.cubin.txt -P /home/conda/feedstock_root/build_artifacts/pytorch-recipe_1645486153516/work/build/third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir/nccl/gloo_cuda_generated_nccl.cu.o.Release.cmake
  /home/conda/feedstock_root/build_artifacts/pytorch-recipe_1645486153516/_build_env/x86_64-conda-linux-gnu/include/c++/10.3.0/chrono: In substitution of 'template<class _Rep, class _Period> template<class _Period2> using __is_harmonic = std::__bool_constant<(std::ratio<((_Period2::num / std::chrono::duration<_Rep, _Period>::_S_gcd(_Period2::num, _Period::num)) * (_Period::den / std::chrono::duration<_Rep, _Period>::_S_gcd(_Period2::den, _Period::den))), ((_Period2::den / std::chrono::duration<_Rep, _Period>::_S_gcd(_Period2::den, _Period::den)) * (_Period::num / std::chrono::duration<_Rep, _Period>::_S_gcd(_Period2::num, _Period::num)))>::den == 1)> [with _Period2 = _Period2; _Rep = _Rep; _Period = _Period]':
  /home/conda/feedstock_root/build_artifacts/pytorch-recipe_1645486153516/_build_env/x86_64-conda-linux-gnu/include/c++/10.3.0/chrono:473:154:   required from here
  /home/conda/feedstock_root/build_artifacts/pytorch-recipe_1645486153516/_build_env/x86_64-conda-linux-gnu/include/c++/10.3.0/chrono:428:27: internal compiler error: Segmentation fault
    428 |  _S_gcd(intmax_t __m, intmax_t __n) noexcept
        |                           ^~~~~~
  Please submit a full bug report,
  with preprocessed source if appropriate.
  See <[https://gcc.gnu.org/bugs/>](https://gcc.gnu.org/bugs/%3E) for instructions.
  ```

**Comment by hmaarrfk** [comment]
thank you. Will use lief dev in the next release

**Comment by hmaarrfk** [comment]
Thank you all for the discussion. I am using this as a baseline for 1.11 in
https://github.com/conda-forge/pytorch-cpu-feedstock/pull/95

**Pull request closed without merging**
