### PR TITLE
Updated version to 1.4.0

### PR DESCRIPTION
**Pull request by eggzilla**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by eggzilla** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
@conda-forge/pytorch-cpu, thoughts?

**Comment by rgommers** [comment]
I'd shelve this repo, it's a distraction.

`conda install pytorch cpuonly -c pytorch` should work.

**Comment by hadim** [comment]
This repo is useful to use it in recipe that require pytorch. During the build process we might want to test against pytorch 1.4.

Or is that possible to use pytorch from the pytorch channel during the build of another package?

**Comment by hmaarrfk** [comment]
I agree that the recipe is useful.

I still don't know how to get a bigger machine for windows compilation

**Comment by hadim** [comment]
I realize reading this thread that what's needed actually is the support of a pytorch package in conda forge by pytorch folks: https://github.com/conda-forge/pytorch-cpu-feedstock/issues/7#issuecomment-538253388

It does not seem that it's going to happen anytime soon... and it's too bad IMO. In the meantime, all the packages using pytorch on conda-forge are built and test against pytorch 1.1. In the long term, this is a bad situation and will likely lead to a lot of issues.

**Comment by apcamargo** [comment]
Late for the discussion, but I'd like to add that Bioconda recipes can only depend on packages that are in the Bioconda or Conda-Forge channels so this recipe is also important for building recipes in Bioconda that depend on PyTorch.

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
Lets try building again in #20 

Most people wanted users not to be suprised by the low performance.

I got stuck on building resources when pytorch updated.

I would also lkike something to "test" software, even if it doesn't have the high performance.

Pretty useful for laptops.

**Pull request closed without merging**
