### PR TITLE
WIP: Disable: Caffe2

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
seems that caffe2 avoids 50 mins of build time on the CPU build.

**Comment by IvanYashchuk** [comment]
Mark, `--threads` was added only in CUDA 11.3. PyTorch already uses custom parallel nvcc (`pytorch/tools/fast_nvcc/fast_nvcc.py`), the details about it are here: https://samestep.com/2021/02/20/parallelizing-nvcc.html

**Comment by hmaarrfk** [comment]
Ah sorry, i didn't revert enough.

**Comment by hmaarrfk** [comment]
@IvanYashchuk if you can think of anything else that might make this build pass in time please do suggest.

**Comment by benjaminrwilson** [comment]
@IvanYashchuk, is this flag in `11.2` something different than `11.3+`?

https://docs.nvidia.com/cuda/archive/11.2.0/cuda-compiler-driver-nvcc/index.html#options-for-guiding-compiler-driver-threads

**Pull request closed without merging**
