### PR TITLE
V1.2

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Previous windows builds have taken 3:40
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=48916

**Comment by hmaarrfk** [comment]
Apparently the windows linker is out of memory..... Is that disk or RAM

**Comment by hmaarrfk** [comment]
@sodre  @conda-forge/core does anybody have an idea on how I can have more RAM for the windows build?

**Comment by mariusvniekerk** [comment]
Basically build it locally :(

**Comment by hmaarrfk** [comment]
I could do that. But I wouldn't have the rights to upload.... I could
upload to my own channel, then you could reupload.

**Comment by jakirkham** [comment]
Maybe @minrk has ideas as I think he’s had similar issues with `npm`. 🙂

**Comment by ocefpaf** [comment]
> I could do that. But I wouldn't have the rights to upload.... I could upload to my own channel, then you could reupload.

That works. For Qt we do something similar, or you can just add a link with a checksum here and ask for a core member to upload it.

**Comment by ocefpaf** [comment]
@conda-forge/core we should start documenting all the packages we have trouble building on CIs to make it easier to write proposals to as for more resources. Not sure where we should do that though. An issue? Docs?

**Comment by CJ-Wright** [comment]
Issue against GitHub.io?

**Comment by jakirkham** [comment]
:+1:

**Comment by minrk** [comment]
> Maybe @minrk has ideas as I think he’s had similar issues with nodejs. 🙂

Afraid not. nodejs is no longer built on Windows after months of on-and-off trying. It is repackaging official binaries. see https://github.com/conda-forge/nodejs-feedstock/issues/65 , https://github.com/conda-forge/nodejs-feedstock/pull/52, and https://github.com/conda-forge/nodejs-feedstock/pull/51 for attempts at reducing resource usage. But it only goes up with each node release.

**Pull request closed without merging**
