### PR TITLE
WIP: Fix tests

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@rgrommers locally i get a little further than on the CI:

```
Running test_functional_autograd_benchmark ... [2021-11-16 23:00:06.229518]
Executing ['/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1637095386655/_test_env_placehold_placehold_pl
acehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol
d_placehold_placehold_placehold_p/bin/python', 'test_functional_autograd_benchmark.py'] ... [2021-11-16 23:00:06.229
568]
python: can't open file '/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1637095386655/test_tmp/test/../be
nchmarks/functional_autograd_benchmark/functional_autograd_benchmark.py': [Errno 2] No such file or directory
Fs
======================================================================
FAIL: test_fast_tasks (__main__.TestFunctionalAutogradBenchmark)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1637095386655/test_tmp/test/test_functional_autogr
ad_benchmark.py", line 45, in test_fast_tasks
    self._test_runner(task)
  File "/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1637095386655/test_tmp/test/test_functional_autogr
ad_benchmark.py", line 32, in _test_runner
    self.assertTrue(res.returncode == 0)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 2 tests in 0.024s
```

Is this expected?

**Comment by hmaarrfk** [comment]
@rgommers

**Comment by hmaarrfk** [comment]
Sorry for the ping. Seems like the benchmarks weren't included.

We can probably exclude them from the tests:
https://github.com/pytorch/pytorch/blob/master/test/run_test.py#L682

**Comment by rgommers** [comment]
Agreed, no point running the benchmarks in CI.

**Comment by hmaarrfk** [comment]
```
======================================================================
ERROR: test_all_input_nodes (__main__.TestFX)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1637117336704/test_tmp/test/test_fx.py", line 142, in setUp
    torch.ops.load_library(str(lib_file_path))
  File "/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1637117336704/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl
acehold_placehold_placehold_p/lib/python3.9/site-packages/torch/_ops.py", line 110, in load_library
    ctypes.CDLL(path)
  File "/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1637117336704/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl
acehold_placehold_placehold_p/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/conda/feedstock_root/build_artifacts/pytorch-recipe_1637117336704/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p
lacehold_placehold_placehold_p/lib/python3.9/site-packages/torch/build/lib/libtorchbind_test.so: cannot open shared object file: No such file or directory
```

**Comment by hmaarrfk** [comment]
Seems like the jit is giving trouble.

```
WARNING: The shape inference of prim::PadPacked type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
..............s............s......s.......................sss....................s............................s.s.....s../home/conda/feedstock_root/build_artifacts/pytorch-recipe_1637131636278/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.9/site-packages/torch/jit/annot
ations.py:289: UserWarning: TorchScript will treat type annotations of Tensor dtype-specific subtypes as if they are normal Tensors. dtype constraints are not enforced in compilation either.
  warnings.warn("TorchScript will treat type annotations of Tensor "
...ss....s.......<string>:4: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1637131636278/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py:400: UserWarning: Casting complex values to real discards the imaginary part (Triggered internal
ly at  /home/conda/feedstock_root/build_artifacts/pytorch-recipe_1637131636278/work/aten/src/ATen/native/Copy.cpp:244.)
  return callable(*args, **kwargs)
..............................s......s........s.......................s..............s...............................................................................s............................................s...........................s.....x.........................../home/conda/feedstock_root/build_artifacts/pytorch-recipe_1637131636278/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_plac
ehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.9/site-packages/torch/onnx/utils.py:50: UserWarning: You are exporting the model to ONNX while in training mode with 'train' parameter not specified. The model will default to inference mode export. If you wish to export a training amenable ONNX model, specify training=TrainingMode.TRAINING or tra
ining=TrainingMode.PRESERVE (to preserve the original model state) in torch.onnx.export().
  warnings.warn("You are exporting the model to ONNX while in training mode with "
..................graph(%self : __torch__.jit.test_tracer.Bar,
      %x.1 : Double(3, 2, strides=[2, 1], requires_grad=0, device=cpu),
      %y.1 : Double(1, 2, strides=[2, 1], requires_grad=0, device=cpu)):
  %x : Double(3, 2, strides=[2, 1], requires_grad=0, device=cpu) = aten::relu(%x.1) # $SRC_DIR/test/jit/test_tracer.py:1423:0
  %y : Double(1, 2, strides=[2, 1], requires_grad=0, device=cpu) = aten::relu(%y.1) # $SRC_DIR/test/jit/test_tracer.py:1424:0
  %7 : (Double(1, 2, strides=[2, 1], requires_grad=0, device=cpu), Double(3, 2, strides=[2, 1], requires_grad=0, device=cpu)) = ^Foo()(%x, %y) # $SRC_DIR/test/jit/test_tracer.py:1425:0
  %8 : Double(1, 2, strides=[2, 1], requires_grad=0, device=cpu), %9 : Double(3, 2, strides=[2, 1], requires_grad=0, device=cpu) = prim::TupleUnpack(%7)
  %10 : (Double(1, 2, strides=[2, 1], requires_grad=0, device=cpu), Double(3, 2, strides=[2, 1], requires_grad=0, device=cpu)) = prim::TupleConstruct(%8, %9)
  return (%10)

.............................s..................................../home/conda/feedstock_root/build_artifacts/pytorch-recipe_1637131636278/test_tmp/test/jit/test_types.py:40: DeprecationWarning: Please use assertEqual instead.
  self.assertEquals(expected, scripted)
.............[W ir_emitter.cpp:4093] Warning: List consists of heterogeneous types, which means that it has been typed as containing Union[int, str]. To use any of the values in this List, it will be necessary to add an `assert isinstance` statement before first use to trigger type refinement.
  File "/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1637131636278/test_tmp/test/jit/test_typing.py", line 168
        def fn():
            l1 = [1, 2, "foo", 3]
                 ~~~~~~~~~~~~~~~ <--- HERE
            l2 = ["foo", "bar", "baz", "qux"]
            d: Dict[int, str] = {k : v for k, v in zip(l1, l2)}
 (function emitListLiteral)
.[W ir_emitter.cpp:4093] Warning: List consists of heterogeneous types, which means that it has been typed as containing Union[int, str]. To use any of the values in this List, it will be necessary to add an `assert isinstance` statement before first use to trigger type refinement.
  File "/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1637131636278/test_tmp/test/jit/test_typing.py", line 182
        def fn():
            l1 = ["foo", "bar", "baz", "qux"]
            l2 = [1, 2, "foo", 3]
                 ~~~~~~~~~~~~~~~ <--- HERE
            d: Dict[str, int] = {k : v for k, v in zip(l1, l2)}
            return d
 (function emitListLiteral)
.[W ir_emitter.cpp:4434] Warning: Dict values consist of heterogeneous types, which means that they have been typed as `Any`. To use any of the values in the Dist, it will be necessary to add an `assert isinstance` statement before first use to trigger type refinement.
  File "<string>", line 2
def fn(x):
    d = {"foo": torch.tensor(2),
         ~~~~~~~~~~~~~~~~~~~~~~~
         "bar": {"23": torch.tensor(3)}}
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    d["baz"] = x
    t = d["foo"]
 (function emitSimpleExpr)
[W ir_emitter.cpp:4434] Warning: Dict values consist of heterogeneous types, which means that they have been typed as `Any`. To use any of the values in the Dist, it will be necessary to add an `assert isinstance` statement before first use to trigger type refinement.
  File "/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1637131636278/test_tmp/test/jit/test_typing.py", line 151
        def fn(x):
            d = {"foo": torch.tensor(2),
                ~~~~~~~~~~~~~~~~~~~~~~~~
                 "bar": {"23": torch.tensor(3)}}
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
            d["baz"] = x
            t = d["foo"]
 (function emitSimpleExpr)
.[W ir_emitter.cpp:1638] Warning: Dict values consist of heterogeneous types, which means that they have been typed as being Union[Tensor, Dict[str, Tensor]]. To use any of the values in this dict, it will be necessary to add an `assert isinstance` statement before first use to trigger type refinement. The first non-matching element was typed as Union[Tensor, Dict[str, Tensor]], while the elements  before it were U
nion[Tensor, Dict[str, Tensor]]
  File "<string>", line 2
def fn(x):
    d = dict(foo=torch.tensor(2),
        ~~~~~~~~~~~~~~~~~~~~~~~~~
             bar={"23": torch.tensor(3)})
             ~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    d["baz"] = x
    t = d["foo"]
 (function operator())
[W ir_emitter.cpp:1638] Warning: Dict values consist of heterogeneous types, which means that they have been typed as being Union[Tensor, Dict[str, Tensor]]. To use any of the values in this dict, it will be necessary to add an `assert isinstance` statement before first use to trigger type refinement. The first non-matching element was typed as Union[Tensor, Dict[str, Tensor]], while the elements  before it were Un
ion[Tensor, Dict[str, Tensor]]
  File "/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1637131636278/test_tmp/test/jit/test_typing.py", line 134
        def fn(x):
            d = dict(foo=torch.tensor(2),
                ~~~~~~~~~~~~~~~~~~~~~~~~~
                     bar={"23": torch.tensor(3)})
                     ~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
            d["baz"] = x
            t = d["foo"]
 (function operator())
................................................/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1637131636278/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.9/site-packages/torch/_jit_internal.py:1132: UserWarning: The inner type of a container is lost when cal
ling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "
............................[W ir_emitter.cpp:4093] Warning: List consists of heterogeneous types, which means that it has been typed as containing Union[Tensor, int]. To use any of the values in this List, it will be necessary to add an `assert isinstance` statement before first use to trigger type refinement.
  File "<string>", line 3

def fn():
    x: Union[List[str], List[torch.Tensor]] = [torch.add(1, x) for x in [torch.arange(5), 1]]
                                                                        ~~~~~~~~~~~~~~~~~~~ <--- HERE
    if torch.jit.isinstance(x, List[torch.Tensor]):
        x.append(torch.tensor(3))
 (function emitListLiteral)
[W ir_emitter.cpp:4093] Warning: List consists of heterogeneous types, which means that it has been typed as containing Union[Tensor, int]. To use any of the values in this List, it will be necessary to add an `assert isinstance` statement before first use to trigger type refinement.
  File "<string>", line 3

def fn():
    x: Union[List[torch.Tensor], int] = [torch.add(1, x) for x in [torch.arange(5), 1]]
                                                                  ~~~~~~~~~~~~~~~~~~~ <--- HERE
    if torch.jit.isinstance(x, List[torch.Tensor]):
        x.append(torch.tensor(3))
 (function emitListLiteral)
...................
======================================================================
FAIL: test_if_is_none_dispatch (__main__.TestScript)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1637131636278/test_tmp/test/test_jit.py", line 5898, in test_if_is_none_dispatch
    self.assertTrue(str(test_bool_arith_and.graph).count('if') == 0)
AssertionError: False is not true

----------------------------------------------------------------------
```

At this point. I'm pretty convinced that I can get the tests to run. I'm going to do these mods to test functionality with python 3.10

**Pull request closed without merging**
