### PR TITLE
fixing blas matrix?

### PR DESCRIPTION
**Pull request by ngam**

### CODE REVIEW

**Comment by isuruf** [comment]
Please don't do this. Accelerate is a very experimental backend. Try instead to building with netlib variant which will give openblas by default and then users can use accelerate if they want to experiment.

**Comment by ngam** [comment]
> Please don't do this. Accelerate is a very experimental backend. Try instead to building with netlib variant which will give openblas by default and then users can use accelerate if they want to experiment.

Yes, I agree. Do we just leave them undefined then?

**Comment by isuruf** [comment]
> Yes, I agree. Do we just leave them undefined then?

Not sure. we have to convince CMake to use netlib instead of OpenBLAS.

**Comment by ngam** [comment]
See 970bc53

**Comment by ngam** [comment]
I will build this locally and test. I will post the results here :)

Ideally, I fully agree with the conda-forge knowlwedge base, unless we have to make a CMAKE choice, then I believe we should go for accelerate. Let me dig deeper to find how they define it for pytorch

**Comment by ngam** [comment]
> > Yes, I agree. Do we just leave them undefined then?
> 
> Not sure. we have to convince CMake to use netlib instead of OpenBLAS.

@isuruf see issue #82

**Comment by isuruf** [comment]
> I believe we should go for accelerate.

A huge NO. Accelerate is really buggy and ancient. It's on maintenance mode only. I would not recommend it for anything other than BLAS. Definitely no LAPACK functions.

**Comment by ngam** [comment]
> > I believe we should go for accelerate.
> 
> A huge NO. Accelerate is really buggy and ancient. It's on maintenance mode only. I would not recommend it for anything other than BLAS. Definitely no LAPACK functions.

No, no, the idea is only to replace OpenBLAS with Accelerate. Everything else remains the same, including LAPACK.

**Comment by ngam** [comment]
I am going to close this for now; I have no idea what's causing these issues (it is saying libprotobuf is undefined). We can revisit at a later stage

**Comment by hmaarrfk** [comment]
I'm not sure why we haven't updated. the truth is that manual uploads are really straining on conda-forge core. I'm trying not to ping them too much. but there are many PRs in flight for pytorch ATM

**Comment by ngam** [comment]
Yeah, I am definitely getting out of this mess now! I don't want to add to the pressure especially this seems to be a losing fight with a lot of moving pieces that I personally don't have use for at the moment. These are really, really complicated builds. Very frustrating!!!

**Comment by ngam** [comment]
Do we generally follow the upstream pinning? For example for torchvision below in the table, we need to pin to v1.11.1... which we didin't build
 
<!DOCTYPE html>

torch | torchvision | python
-- | -- | --
main / nightly | main / nightly | >=3.7, <=3.9
1.10.1 | 0.11.2 | >=3.6, <=3.9
1.10.0 | 0.11.1 | >=3.6, <=3.9
1.9.1 | 0.10.1 | >=3.6, <=3.9
1.9.0 | 0.10.0 | >=3.6, <=3.9
1.8.2 | 0.9.2 | >=3.6, <=3.9
1.8.1 | 0.9.1 | >=3.6, <=3.9
1.8.0 | 0.9.0 | >=3.6, <=3.9
1.7.1 | 0.8.2 | >=3.6, <=3.9
1.7.0 | 0.8.1 | >=3.6, <=3.8


<br class="Apple-interchange-newline">

**Comment by hmaarrfk** [comment]
hmm oops. yeah. we do try.

**Comment by ngam** [comment]
```
source:
  # for local testing use a tarball including submodules
  git_url: https://github.com/pytorch/pytorch.git
  git_tag: {{ commit }}
  patches:
    - fix_dispatch_apply_auto.patch
```

Are we not using a tar here because of the 3rd party stuff imbedded as submodules? I can volunteer to tidy that up --- I following a tar ball approach is more efficient and clearly imo

**Comment by hmaarrfk** [comment]
How do you keep all the submodules up to date? Feel free to take a stab at it.

**Comment by ngam** [comment]
> > I believe we should go for accelerate.
> 
> A huge NO. Accelerate is really buggy and ancient. It's on maintenance mode only. I would not recommend it for anything other than BLAS. Definitely no LAPACK functions.

Can you elaborate? It seems supported as far as I can tell: https://developer.apple.com/documentation/accelerate

**Comment by rgommers** [comment]
> No, no, the idea is only to replace OpenBLAS with Accelerate. Everything else remains the same, including LAPACK.

I think you are missing a point here. Both OpenBLAS and Accelerate provide BLAS _and_ LAPACK.



> Can you elaborate? It seems supported as far as I can tell: https://developer.apple.com/documentation/accelerate

See for example https://github.com/scipy/scipy/wiki/Dropping-support-for-Accelerate. Some bugs have been fixed, but Accelerate is still stuck on the ancient LAPACK 3.2.1.

**Comment by ngam** [comment]
> I think you are missing a point here. Both OpenBLAS and Accelerate provide BLAS _and_ LAPACK

Yes, sorry, I was mislead by my work on mxnet where it was printing them out differently (or maybe borrowing them from different place?). See this comment: https://github.com/conda-forge/pytorch-cpu-feedstock/pull/84#issuecomment-1019815924

**Comment by ngam** [comment]
> Both OpenBLAS and Accelerate provide BLAS _and_ LAPACK

Okay, I was under the impression we are able to do this very easily, but maybe I am completely wrong: https://github.com/scipy/scipy/wiki/Dropping-support-for-Accelerate#keep-using-accelerate-blas-but-shadow-lapack

**Comment by ngam** [comment]
Let me double check how it is doing it in my mxnet build, please have a look if you have time: https://github.com/conda-forge/staged-recipes/pull/17620

**Comment by ngam** [comment]
@rgommers, I saw your name around this discussion about Accelerate; from your expert opinion, what should we do in general here (in conda-forge) if the only two options are OpenBLAS and Accelerate? Do I get your stance correctly below?

- Use OpenBLAS (and ignore Accelerate) if LAPACK is important (utilized enough in a given package)
- Use Accelerate (and ignore OpenBLAS) if LAPACK is unimportant (not really utilized in a given package)

Some reports indicate at least double the performance when using Accelerate, but we would want to be careful such that we are not messing up people's environments even for that gain in performance.  I also opened an issue upstream at PyTorch to see what they think and if we can run some tests to establish a preference.

**Comment by isuruf** [comment]
@ngam, you are complicating this way more than it needs to be. We should just build with `netlib` variant and let the user decide between OpenBLAS and Accelerate.

**Comment by ngam** [comment]
> @ngam, you are complicating this way more than it needs to be. We should just build with netlib variant and let the user decide between OpenBLAS and Accelerate.

Okay, thanks @isuruf. I can try that in the future once we have other more pressing issues sorted here. But I am still uncertain we can pull it off; I need to read the notes in the conda-forge knowledge base and see if they necessarily conflict with PyTorch/MXNet/etc. and their CMake processes.

**Comment by ulupo** [comment]
> We should just build with netlib variant and let the user decide between OpenBLAS and Accelerate.

... and is the idea that the user would opt in Accelerate by as per https://conda-forge.org/docs/maintainer/knowledge_base.html#switching-blas-implementation ?

**Comment by ngam** [comment]
> > We should just build with netlib variant and let the user decide between OpenBLAS and Accelerate.
> 
> ... and is the idea that the user would opt in Accelerate as per [standard instructions for switching](https://conda-forge.org/docs/maintainer/knowledge_base.html#switching-blas-implementation)?

Yes, and in this case, PyTorch does indeed fully support Accelerate and so it should work fine.

**Comment by hmaarrfk** [comment]
excited to see a PR! In the past, we've used the test phase, and there chose different implementations of blas with selectors based on the python version.

Exciting!

**Comment by ngam** [comment]
Yes, will do soon @hmaarrfk. I just want to dig deeper a little bit, I opened an issue upstream to discuss and their response is still unclear (though they are responsive and helpful).

Btw, I think we may be doing a better job packaging this than they do --- I think they drop MKL in their cuda builds among other things, but they have no reason to, I think. So thank you for all your work!!

**Pull request closed without merging**
