### PR TITLE
Windows Build

### PR DESCRIPTION
**Pull request by hmaarrfk**
Follow azure builds: https://dev.azure.com/conda-forge/feedstock-builds/_build?definitionId=2441&_a=summary

Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

@mariusvniekerk can we add azure to the checks at the bottom here?

**Comment by hmaarrfk** [comment]
image

**Comment by hmaarrfk** [comment]
Maybe this: https://github.com/pytorch/pytorch/issues/14410

**Comment by mariusvniekerk** [comment]
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=16342

**Comment by hmaarrfk** [comment]
omg, i think it actually worked. I want to add the patch to OSX and Linux, so I'm going to enable all the builds soon.

@sodre seems to be working.

Now time to think about the pytorch metapackage.

**Comment by hmaarrfk** [comment]
Merging this! Now time to upgrade to a newer version!

**Pull request merged**
