### PR TITLE
implement accelerate for osx-arm64

### LINKED ISSUE #82: pytorch bombs if `"libblas=*=*accelerate"`
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

pytorch bombs if `"libblas=*=*accelerate"`

reference: https://conda-forge.org/docs/maintainer/knowledge_base.html#blas

reference: https://github.com/pytorch/pytorch/blob/ea4d98388500496f04fd6a814b134c4242160267/cmake/Modules/FindBLAS.cmake#L122-L135

Not sure if this part of meta makes sense:

https://github.com/conda-forge/pytorch-cpu-feedstock/blob/5711a74b66df37cd4f5e879f111c25389052519f/recipe/meta.yaml#L69-L88

Here's the error when enforcing `"libblas=*=*accelerate"`:

```
Python 3.9.9 | packaged by conda-forge | (main, Dec 20 2021, 02:41:06) 
[Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ngam/.Mambaforge-MacOSX-arm64/envs/ptps/lib/python3.9/site-packages/torch/__init__.py", line 197, in <module>
    from torch._C import *  # noqa: F403
ImportError: dlopen(/Users/ngam/.Mambaforge-MacOSX-arm64/envs/ptps/lib/python3.9/site-packages/torch/_C.cpython-39-darwin.so, 0x0002): Library not loaded: @rpath/libopenblas.0.dylib
  Referenced from: /Users/ngam/.Mambaforge-MacOSX-arm64/envs/ptps/lib/python3.9/site-packages/torch/lib/libtorch_python.dylib
  Reason: tried: '/Users/ngam/.Mambaforge-MacOSX-arm64/envs/ptps/lib/python3.9/site-packages/torch/lib/libopenblas.0.dylib' (no such file), '/Users/ngam/.Mambaforge-MacOSX-arm64/envs/ptps/lib/python3.9/site-packages/torch/lib/../../../../libopenblas.0.dylib' (no such file), '/Users/runner/miniforge3/conda-bld/pytorch-recipe_1635217266490/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/libopenblas.0.dylib' (no such file), '/Users/runner/miniforge3/conda-bld/pytorch-recipe_1635217266490/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/libopenblas.0.dylib' (no such file), '/Users/ngam/.Mambaforge-MacOSX-arm64/envs/ptps/lib/python3.9/site-packages/torch/lib/libopenblas.0.dylib' (no such file), '/Users/ngam/.Mambaforge-MacOSX-arm64/envs/ptps/lib/python3.9/site-packages/torch/../../../libopenblas.0.dylib' (no such file), '/Users/runner/miniforge3/conda-bld/pytorch-recipe_1635217266490/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/libopenblas.0.dylib' (no such file), '/Users/runner/miniforge3/conda-bld/pytorch-recipe_1635217266490/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/libopenblas.0.dylib' (no such file), '/Users/ngam/.Mambaforge-MacOSX-arm64/envs/ptps/lib/python3.9/site-packages/torch/lib/libopenblas.0.dylib' (no such file), '/Users/ngam/.Mambaforge-MacOSX-arm64/envs/ptps/lib/python3.9/site-packages/torch/../../../libopenblas.0.dylib' (no such file), '/Users/ngam/.Mambaforge-MacOSX-arm64/envs/ptps/bin/../lib/libopenblas.0.dylib' (no such file), '/Users/ngam/.Mambaforge-MacOSX-arm64/envs/ptps/bin/../lib/libopenblas.0.dylib' (no such file), '/usr/local/lib/libopenblas.0.dylib' (no such file), '/usr/lib/libopenblas.0.dylib' (no such file)

```

---

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

# packages in environment at /Users/ngam/.Mambaforge-MacOSX-arm64/envs/ptps:
#
# Name                    Version                   Build  Channel
aom                       3.2.0                hc470f4d_2    conda-forge
bzip2                     1.0.8                h3422bc3_4    conda-forge
ca-certificates           2021.10.8            h4653dfc_0    conda-forge
cffi                      1.15.0           py39h52b1de0_0    conda-forge
ffmpeg                    4.4.1                hdbd4ad8_0    conda-forge
freetype                  2.10.4               h17b34a0_1    conda-forge
future                    0.18.2           py39h2804cbe_4    conda-forge
gettext                   0.19.8.1          h049c9fb_1008    conda-forge
gmp                       6.2.1                h9f76cd9_0    conda-forge
gnutls                    3.6.13               h706517b_1    conda-forge
icu                       69.1                 hbdafb3b_0    conda-forge
jbig                      2.1               h3422bc3_2003    conda-forge
jpeg                      9d                   h27ca646_0    conda-forge
lame                      3.100             h27ca646_1001    conda-forge
lcms2                     2.12                 had6a04f_0    conda-forge
lerc                      3.0                  hbdafb3b_0    conda-forge
libblas                   3.9.0           13_osxarm64_accelerate    conda-forge
libcblas                  3.9.0           13_osxarm64_accelerate    conda-forge
libcxx                    12.0.1               h168391b_1    conda-forge
libdeflate                1.8                  h3422bc3_0    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgfortran               5.0.0.dev0      11_0_1_hf114ba7_23    conda-forge
libgfortran5              11.0.1.dev0         hf114ba7_23    conda-forge
libiconv                  1.16                 h642e427_0    conda-forge
liblapack                 3.9.0           13_osxarm64_accelerate    conda-forge
libopenblas               0.3.18          openmp_h5dd58f0_0    conda-forge
libpng                    1.6.37               hf7e6567_2    conda-forge
libprotobuf               3.18.1               hccf11d3_0    conda-forge
libtiff                   4.3.0                h74060c4_2    conda-forge
libvpx                    1.11.0               hc470f4d_3    conda-forge
libwebp-base              1.2.2                h3422bc3_1    conda-forge
libxml2                   2.9.12               hedbfbf4_1    conda-forge
libzlib                   1.2.11            hee7b306_1013    conda-forge
llvm-openmp               12.0.1               hf3c4609_1    conda-forge
lz4-c                     1.9.3                hbdafb3b_1    conda-forge
ncurses                   6.3                  hc470f4d_0    conda-forge
nettle                    3.6                  hc6a1b29_0    conda-forge
ninja                     1.10.2               hc021e02_1    conda-forge
numpy                     1.22.0           py39h61a45d2_1    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openh264                  2.1.1                habe5f53_0    conda-forge
openjpeg                  2.4.0                h062765e_1    conda-forge
openssl                   3.0.0                h3422bc3_2    conda-forge
pillow                    8.4.0            py39ha74c66e_0    conda-forge
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
python                    3.9.9           h43b31ca_0_cpython    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytorch                   1.10.0          cpu_py39h7601aee_0    conda-forge
pytorch-cpu               1.10.0          cpu_py39hd610c6a_0    conda-forge
readline                  8.1                  hedafd6a_0    conda-forge
setuptools                60.5.0           py39h2804cbe_0    conda-forge
sleef                     3.5.1                h156473d_2    conda-forge
sqlite                    3.37.0               h72a2b83_0    conda-forge
svt-av1                   0.9.0                hc470f4d_0    conda-forge
tk                        8.6.11               he1e0b03_1    conda-forge
torchvision               0.11.2          py39h743af5b_1_cpu    conda-forge
typing_extensions         4.0.1              pyha770c72_0    conda-forge
tzdata                    2021e                he74cb21_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
x264                      1!161.3030           h3422bc3_1    conda-forge
x265                      3.5                  h666519e_1    conda-forge
xz                        5.2.5                h642e427_1    conda-forge
zlib                      1.2.11            hee7b306_1013    conda-forge
zstd                      1.5.2                h861e0a7_0    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : ptps
    active env location : /Users/ngam/.Mambaforge-MacOSX-arm64/envs/ptps
            shell level : 2
       user config file : /Users/ngam/.condarc
 populated config files : /Users/ngam/.Mambaforge-MacOSX-arm64/.condarc
                          /Users/ngam/.condarc
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.9.9.final.0
       virtual packages : __osx=12.1=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /Users/ngam/.Mambaforge-MacOSX-arm64  (writable)
      conda av data dir : /Users/ngam/.Mambaforge-MacOSX-arm64/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/apple/osx-arm64
                          https://conda.anaconda.org/apple/noarch
                          https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/ngam/.Mambaforge-MacOSX-arm64/pkgs
                          /Users/ngam/.conda/pkgs
       envs directories : /Users/ngam/.Mambaforge-MacOSX-arm64/envs
                          /Users/ngam/.conda/envs
               platform : osx-arm64
             user-agent : conda/4.11.0 requests/2.27.1 CPython/3.9.9 Darwin/21.2.0 OSX/12.1
                UID:GID : 501:20
             netrc file : None
           offline mode : False

```
</details>

### PR DESCRIPTION
**Pull request by ngam**
This PR only changes netlib implementation for osx-arm64. Everything else remains the same. Skipping all builds but osx for confirmation.

Fixes #82 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ngam** [comment]
@hmaarrfk please review if changes are acceptable.

@isuruf could you please double-check if I did this correctly?

Thank you both!!

**Comment by ngam** [comment]
(I will test this locally and put the results here in a bit)

**Comment by hmaarrfk** [comment]
Could you add a constraint like:

```
- blas *=accelerate   # [osx and arm64 and py==38]
- blas *=openblas     # [osx and arm64 and py==39]
```

And run the tests locally? this would somewhat build up a minimal test matrix.

**Comment by ngam** [comment]
> Could you add a constraint like:
> 
> ```
> - blas *=accelerate   # [osx and arm64 and py==38]
> - blas *=openblas     # [osx and arm64 and py==39]
> ```
> 
> And run the tests locally? this would somewhat build up a minimal test matrix.

Yes, but what's the point? We already know what this will lead to: _same exact outcome_. The reason: [568f298](https://github.com/conda-forge/pytorch-cpu-feedstock/pull/88/commits/568f298519d6c54aa9213fe60d8f575507c1fc22). 

If we want to build a matrix, then we need to base it on the CMAKE flag. Happy to go that route, but I believe it's just too much work for nothing -- this is already a challenging build. I think it is better to just default osx-arm to accelerate for now. But if you want me to go ahead and build matrix for arm64, I am happy to do so --- again, it would need to be done with a control flow on the cmake flag, I believe.

**Comment by ngam** [comment]
To clarify: [568f298](https://github.com/conda-forge/pytorch-cpu-feedstock/pull/88/commits/568f298519d6c54aa9213fe60d8f575507c1fc22) removes instructing it to find a specific BLAS. So it goes through its list: MKL, BLIS, Accelerate, and then OpenBLAS (and maybe some others, see here https://github.com/pytorch/pytorch/blob/v1.10.2/cmake/Modules/FindBLAS.cmake). So unless we specify that cmake flag, it will just repeat the same process again: MKL, BLIS, Accelerate, OpenBLAS, etc. --- _note: Accelerate is always part of the macos SDK, so it will always be discovered before OpenBLAS unless instructed otherwise_.

**Comment by hmaarrfk** [comment]
don't we want it to therefore find netlib?

**Comment by ngam** [comment]
> don't we want it to therefore find netlib?

Maybe we can force it to find 'generic'?

```
# Generic BLAS library?
if((NOT BLAS_LIBRARIES)
    AND ((NOT WITH_BLAS) OR (WITH_BLAS STREQUAL "generic")))
  check_fortran_libraries(
  BLAS_LIBRARIES
  BLAS
  sgemm
  ""
  "blas")
  if (BLAS_LIBRARIES)
    set(BLAS_INFO "generic")
  endif(BLAS_LIBRARIES)
endif()
```

https://github.com/pytorch/pytorch/blob/71f889c7d265b9636b93ede9d651c0a9c4bee191/cmake/Modules/FindBLAS.cmake#L279-L291

**Comment by ngam** [comment]
If this 'generic' trick works, we can implement it for all builds...

**Comment by ngam** [comment]
@isuruf does this count as netlib?

```  -- Using BLAS: /Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/usr/lib/libblas.tbd
```

**Comment by ngam** [comment]
I don't think so... https://conda-forge.org/docs/maintainer/knowledge_base.html?highlight=mesa#how-it-works

**Comment by ngam** [comment]
Trying to find the way isuruf implemented this, I remember seeing `.tbd` in his hacks :)

**Comment by ngam** [comment]
https://github.com/conda-forge/blas-feedstock/pull/82/files

**Comment by ngam** [comment]
```
lrwxr-xr-x    1 root  wheel     114 Dec 14 19:47 libblas.tbd -> ../../System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.tbd
```

```
lrwxr-xr-x    1 root  wheel     114 Dec 14 19:47 libcblas.tbd -> ../../System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.tbd
```

I am going to revert back to the default since this won't work I think. I will give it sometime for people to weigh in

**Comment by ngam** [comment]
Or I can build a matrix... will revisit later

**Comment by ngam** [comment]
> * conda smithy recipe-lint .

```
pytorch-cpu-feedstock/recipe$ conda smithy recipe-lint .
. is in fine form
```

🤷

**Comment by ngam** [comment]
@hmaarrfk, I thought about this and did a little more looking around. Now I believe this is likely not worth it and so I am going to abandon this for now. The reason is that this the benefit of defaulting to Accelerate don't really materialize for PyTorch (at least not yet). They're supposedly working on supporting the new Apple GPUs (Metal) and we can try again then. For now, I just think this shouldn't be a priority. 

Closing. Happy to revisit again if other people really want this...

**Comment by hmaarrfk** [comment]
Interesting findings!

**Comment by ngam** [comment]
I think as part of their metal effort, they might reorganize things and so we are just better off waiting until then, especially that this is an osx-arm64 issue/improvement only. They have a big central issue upstream with a lot of annoying Apple fans asking for updates incessantly 😆

**Comment by jkleckner** [comment]
At the risk of necroposting, this approach in numpy with wrappers is interesting [1].
Some of the benchmarks show huge improvement.

Note that MacOS 13.3 improved netlib compatibility [2]:

> The BLAS and LAPACK libraries under the Accelerate framework are now inline with reference version 3.9.1. These new interfaces provide additional functionality and a new ILP64 interface. To use the new interfaces, define ACCELERATE_NEW_LAPACK before including the Accelerate or vecLib headers. For ILP64 interfaces, also define ACCELERATE_LAPACK_ILP64.

[1] https://github.com/numpy/numpy/pull/24053
[2] https://developer.apple.com/documentation/macos-release-notes/macos-13_3-release-notes#New-Features

Cross links to:

[3] https://github.com/conda-forge/pytorch-cpu-feedstock/issues/85
[4] https://github.com/conda-forge/pytorch-cpu-feedstock/issues/82

**Comment by jkleckner** [comment]
> Closing. Happy to revisit again if other people really want this...

A conda environment that includes pytorch forces the use of openblas rather than the up to 10x faster implementation MacOS 13.3 accelerate BLAS [1].  If you don't use pytorch in your conda environment, numpy works great with the accelerate BLAS but you end up having two environments, one for pytorch and GPU and one for numpy and not GPU.

How hard/complex would it be to add pytorch builds specific to MacOS 13.3+ that enable the flags to use the accelerate BLAS?  It is a bit unfortunate that Apple ties this important performance improvement into the OS version...

[1] https://github.com/numpy/numpy/pull/24053

**Comment by isuruf** [comment]
You can already use `conda install pytorch blas=*=*accelerate`. It gives you only BLAS functions with accelerate. LAPACK is still provided by netlib.

**Comment by jkleckner** [comment]
> You can already use `conda install pytorch blas=*=*accelerate`. It gives you only BLAS functions with accelerate. LAPACK is still provided by netlib.

@isuruf I thought I tried that.  I just re-ran this script and get the same output as before my post with the error below.
Attaching the script and perhaps you can point out my error?

```
Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "/opt/homebrew/Caskroom/miniforge/base/envs/try_pytorch_3_10/lib/python3.10/site-packages/torch/__init__.py", line 229, in <module>
    from torch._C import *  # noqa: F403
ImportError: dlopen(/opt/homebrew/Caskroom/miniforge/base/envs/try_pytorch_3_10/lib/python3.10/site-packages/torch/_C.cpython-310-darwin.so, 0x0002): Library not loaded: @rpath/libopenblas.0.dylib
  Referenced from: <51247470-C91F-3562-843D-7DDA002EA002> /opt/homebrew/Caskroom/miniforge/base/envs/try_pytorch_3_10/lib/python3.10/site-packages/torch/lib/libtorch_cpu.dylib
  Reason: tried: '/opt/homebrew/Caskroom/miniforge/base/envs/try_pytorch_3_10/lib/python3.10/site-packages/torch/lib/libopenblas.0.dylib' (no such file), '/opt/homebrew/Caskroom/miniforge/base/envs/try_pytorch_3_10/lib/python3.10/site-packages/torch/lib/../../../../libopenblas.0.dylib' (no such file), '/opt/homebrew/Caskroom/miniforge/base/envs/try_pytorch_3_10/lib/python3.10/site-packages/torch/lib/libopenblas.0.dylib' (no such file), '/opt/homebrew/Caskroom/miniforge/base/envs/try_pytorch_3_10/lib/python3.10/site-packages/torch/lib/../../../../libopenblas.0.dylib' (no such file), '/opt/homebrew/Caskroom/miniforge/base/envs/try_pytorch_3_10/lib/python3.10/site-packages/torch/lib/libopenblas.0.dylib' (no such file), '/opt/homebrew/Caskroom/miniforge/base/envs/try_pytorch_3_10/lib/python3.10/site-packages/torch/lib/../../../../libopenblas.0.dylib' (no such file), '/opt/homebrew/Caskroom/miniforge/base/envs/try_pytorch_3_10/lib/python3.10/site-packages/torch/lib/libopenblas.0.dylib' (no such file), '/opt/homebrew/Caskroom/miniforge/base/envs/try_pytorch_3_10/lib/python3.10/site-packages/torch/lib/../../../../libopenblas.0.dylib' (no such file), '/opt/homebrew/Caskroom/miniforge/base/envs/try_pytorch_3_10/lib/python3.10/site-packages/torch/lib/libopenblas.0.dylib' (no such file), '/opt/homebrew/Caskroom/miniforge/base/envs/try_pytorch_3_10/lib/python3.10/site-packages/torch/../../../libopenblas.0.dylib' (no such file), '/opt/homebrew/Caskroom/miniforge/base/envs/try_pytorch_3_10/lib/python3.10/site-packages/torch/lib/libopenblas.0.dylib' (no such file), '/opt/homebrew/Caskroom/miniforge/base/envs/try_pytorch_3_10/lib/python3.10/site-packages/torch/../../../libopenblas.0.dylib' (no such file), '/opt/homebrew/Caskroom/miniforge/base/envs/try_pytorch_3_10/bin/../lib/libopenblas.0.dylib' (no such file), '/opt/homebrew/Caskroom/miniforge/base/envs/try_pytorch_3_10/bin/../lib/libopenblas.0.dylib' (no such file), '/usr/local/lib/libopenblas.0.dylib' (no such file), '/usr/lib/libopenblas.0.dylib' (no such file, not in dyld cache)
```

[try_pytorch_alone.txt](https://github.com/conda-forge/pytorch-cpu-feedstock/files/12210903/try_pytorch_alone.txt)

**Comment by jkleckner** [comment]
Side note, this is a great read for context of these libraries: https://pypackaging-native.github.io/key-issues/native-dependencies/blas_openmp/

**Comment by isuruf** [comment]
@jkleckner, ah I thought we had https://github.com/conda-forge/pytorch-cpu-feedstock/pull/175 merged. Until that PR is merged you can do `ln -sf $CONDA_PREFIX/lib/libcblas.3.dylib $CONDA_PREFIX/lib/libopenblas.0.dylib`

**Comment by jkleckner** [comment]
@isuruf Wow, thanks!  That got it going.  Now the numpy runs fast and pytorch still uses the GPU.  I used one of these benchmarks [1] to try it out.  Hopefully, pytorch fallback to CPU from GPU will reap the speed benefits.  You mention that it is still LAPACK via netlib rather than accelerate, true?  This [2] suggests a 4x difference in speed when netlib is the BLAS, but if netlib LAPACK is using the underlying BLAS then it might not be so big a difference.  Those benchmarks [2] don't really exercise LAPACK apis directly.

[1] https://github.com/lucadiliello/pytorch-apple-silicon-benchmarks

`python tests/transformers_sequence_classification.py --device mps --pre_trained_name bert-base-cased --batch_size 64 --mode training --steps 100 --sequence_length 128`
Took 86s on M1 Max and saturated the GPUs.

[2] https://stackoverflow.com/a/70255105

**Comment by jkleckner** [comment]
After your symlink, these are the dylibs.  (The symlink could be local).
```
$ ll  *vec*.dylib *blas*.dylib  *lapa*.dylib
lrwxr-xr-x  1 jim  admin    22B Jul 30 19:29 libblas.3.dylib -> libvecLibFort-ng.dylib
lrwxr-xr-x  1 jim  admin    22B Jul 30 19:29 libblas.dylib -> libvecLibFort-ng.dylib
lrwxr-xr-x  1 jim  admin    22B Jul 30 19:29 libcblas.3.dylib -> libvecLibFort-ng.dylib
lrwxr-xr-x  1 jim  admin    22B Jul 30 19:29 libcblas.dylib -> libvecLibFort-ng.dylib
-rwxrwxr-x  5 jim  admin   5.8M Jun  4 19:10 liblapack-netlib.3.9.0.dylib
lrwxr-xr-x  1 jim  admin    22B Jul 30 19:29 liblapack.3.dylib -> libvecLibFort-ng.dylib
lrwxr-xr-x  1 jim  admin    22B Jul 30 19:29 liblapack.dylib -> libvecLibFort-ng.dylib
-rwxrwxr-x  5 jim  admin   1.6M Jun  4 19:10 liblapacke-netlib.3.9.0.dylib
lrwxr-xr-x  1 jim  admin    22B Jul 30 19:29 liblapacke.3.dylib -> libvecLibFort-ng.dylib
lrwxr-xr-x  1 jim  admin    22B Jul 30 19:29 liblapacke.dylib -> libvecLibFort-ng.dylib
lrwxr-xr-x  1 jim  admin    80B Jul 30 21:00 libopenblas.0.dylib -> /opt/homebrew/Caskroom/miniforge/base/envs/try_pytorch_3_10/lib/libcblas.3.dylib
-rwxrwxr-x  5 jim  admin    72K Jun  4 19:10 libvecLibFort-ng.dylib
```

**Comment by jkleckner** [comment]
I can confirm that the script runs correctly after the merge of #175 with numpy executing fast and GPU on arm64 working.
Thank you.

**Pull request closed without merging**
