### PR TITLE
Update to 2.4.0 and add libpytorch.so to lib location

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
This seems to work. I’m trying 11.8 locally with Isuru’s patch for libpytorch  

after that I’ll push here for the CIs to build the whole matrix.

**Comment by hmaarrfk** [comment]
@jeongseok-meta  I think i got the changes that you requested for `libpytorch`.

cc: @h-vetinari @isuruf for an other set of eyes. If all is green I hope to merge on friday. LMK

**Comment by jeongseok-meta** [comment]
@hmaarrfk Awesome, thank you for sorting the issue out!

**Comment by hmaarrfk** [comment]
alright, lets merge so we can take some of the heat on friday.

**Comment by jeongseok-meta** [comment]
Great! Do we still need https://github.com/conda-forge/pytorch-cpu-feedstock/pull/246, as I see that the changes are already included in this PR?

**Comment by hmaarrfk** [comment]
We will have to start a pytorch 2.4.0 migration tomorrow, so it may take a day or 3 for all the changes to propogate if you have dependnecies that depend on pytorch

**Comment by h-vetinari** [comment]
Sorry I missed the ping, and thanks for fixing this!

**Pull request merged**
