### PR TITLE
Try to update to 2.1.0 and python 3.12

### PR DESCRIPTION
**Pull request by hmaarrfk**
All linux logs:
[log_files.zip](https://github.com/conda-forge/pytorch-cpu-feedstock/files/13273380/log_files.zip)

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@xhochy can i make it so that all the linux builds timeout? I can build all of those myself.

**Comment by hmaarrfk** [comment]
while the osx is anticipated to pass, the linux builds will take longer since i'm running them on a single machine.

**Comment by hmaarrfk** [comment]
[log_files.zip](https://github.com/conda-forge/pytorch-cpu-feedstock/files/13273380/log_files.zip)

**Comment by hmaarrfk** [comment]
Any objections to merging this?

**Comment by Tobias-Fischer** [comment]
Not from me, this is very exciting, thanks a lot for all your efforts, @hmaarrfk!!!

**Comment by jakirkham** [comment]
Thanks Mark! 🙏

**Comment by jakirkham** [comment]
Sorry had one follow up question. Did we build packages for CUDA 12 as well? Or are those pending?

**Comment by hmaarrfk** [comment]
they half exist..... the `pytorch-gpu` is built, but the `pytorch` seems to be missing...

**Comment by hmaarrfk** [comment]
[linux_64_blas_implmklc_compiler_version12cuda_compilercuda-nvcccuda_compiler_version12.0cxx_compiler_version12numpy1.26python3.12.____cpython-log.txt](https://github.com/conda-forge/pytorch-cpu-feedstock/files/13274234/linux_64_blas_implmklc_compiler_version12cuda_compilercuda-nvcccuda_compiler_version12.0cxx_compiler_version12numpy1.26python3.12.____cpython-log.txt)

**Comment by hmaarrfk** [comment]
sorry, they are broken. i should have looked more closely. it is hard with the sheer numberof builds....

**Comment by hmaarrfk** [comment]
```
  -- Unable to find cublas_v2.h in either "/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1699186934304/_build_env/targets/x86_64-linux/include" or "/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1699186934304/_build_env/math_libs/include"
  -- Found CUDAToolkit: /home/conda/feedstock_root/build_artifacts/pytorch-recipe_1699186934304/_build_env/targets/x86_64-linux/include (found version "12.0.76")
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
  -- Check if compiler accepts -pthread
  -- Check if compiler accepts -pthread - yes
  -- Found Threads: TRUE
  CMake Error at cmake/public/cuda.cmake:65 (message):
    Found two conflicting CUDA installs:

    V12.0.76 in
    '/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1699186934304/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/targets/x86_64-linux/include'
    and

    V12.0.76 in
    '/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1699186934304/_build_env/targets/x86_64-linux/include'
  Call Stack (most recent call first):
    cmake/Dependencies.cmake:44 (include)
    CMakeLists.txt:722 (include)


```

**Comment by jakirkham** [comment]
Completely understand

Thanks Mark! 🙏

Interesting IIUC this worked in 2.0.0 and then started failing with 2.1.0. Wonder what caused the change

**Comment by jakirkham** [comment]
Think this line might be part of the issue

https://github.com/conda-forge/pytorch-cpu-feedstock/blob/dc47045982267ca9f1b93c65887bac39dc668ec6/recipe/build_pytorch.sh#L155

`$CUDA_HOME` is no longer defined in CUDA 12. Think if we don't set this in the CUDA 12 case, the logic already baked into `cuda-nvcc` for CMake should take affect

If that doesn't work for some reason, am happy to discuss alternatives

**Comment by jakirkham** [comment]
cc @RaulPPelaez (for awareness)

**Comment by hmaarrfk** [comment]
> Interesting IIUC this worked in 2.0.0 and then started failing with 2.1.0. Wonder what caused the change

I feel like it also worked when I tested things for 2.1.0, but then eventually started to stop working...

**Comment by jakirkham** [comment]
More discussion in PR: https://github.com/conda-forge/pytorch-cpu-feedstock/pull/203

**Pull request merged**
