### PR TITLE
1.7.1

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
is it possible to "rebase" to make review more focused.

Thanks for moving this through!

**Comment by hmaarrfk** [comment]
@chrisburr do you really want to build 1.6 or sould we skip ahead to 1.7 for GPU builds?

**Comment by hmaarrfk** [comment]
I've been pushing that backports become python version dependent, so that downstream packages don't have to worry to add selectors.

https://github.com/conda-forge/dataclasses-feedstock/blob/master/recipe/meta.yaml

It seems that dataclasses has evolved a little to include "noop" scripts.

**Comment by isuruf** [comment]
that might be useful for noarch python packages, but since this pytorch is not a noarch package, there's no point pulling it in even if it's empty.

**Comment by chrisburr** [comment]
> @chrisburr do you really want to build 1.6 or sould we skip ahead to 1.7 for GPU builds?

I didn't see  this until after I'd already built an uploaded them, but yes minimising the number of builds would be good both from a CPU perspective and to avoid adding unnecessary data to the main channel (each build is ~7GB).

**Comment by hmaarrfk** [comment]
One linux build dialed but I think it is ok.

I'll have to learn to restart builds one day.

I need to make sure the windows builds all failed due to timeout, then I'll merge.

Thanks @isuruf

**Comment by chrisburr** [comment]
The Windows issues are real failures:

```
    CMake Error at CMakeLists.txt:237 (find_library):
      Could not find libuv_tmp_LIBRARY using the following names: uv, libuv
```

**Comment by hmaarrfk** [comment]
then we need https://github.com/conda-forge/libuv-feedstock/pull/47

**Comment by hmaarrfk** [comment]
There may be other ways to do it, https://github.com/pytorch/pytorch/blob/master/CMakeLists.txt#L255

but we can probably try to use uv.

**Comment by hmaarrfk** [comment]
```
    ..\aten\src\ATen/core/boxing/impl/boxing.h(100): error C2066: cast to function type is illegal
```
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=253804&view=logs&j=e5cdccbf-4751-5a24-7406-185c9d30d021&t=66e4a587-a723-53e9-873c-6c9a2c5971ea&l=6684

**Comment by hmaarrfk** [comment]
Could be related to this. https://github.com/pytorch/pytorch/issues/48763

Apparently they upgraded MSVC and it went away.

**Comment by hmaarrfk** [comment]
thanks for all the hard work and upstreaming patches.

```
    CMake Error at third_party/fbgemm/CMakeLists.txt:50 (message):
      A compiler with AVX512 support is required.
```

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by isuruf** [comment]
This is ready

**Comment by hmaarrfk** [comment]
Thanks, this looks great.

We should consider renaming this repo

**Comment by hmaarrfk** [comment]
@chrisburr building this package for CUDA would be appreciated.

@isuruf are you taking charge of building for windows?

**Comment by chrisburr** [comment]
Done

* [linux_64_cuda_compiler_version9.2numpy1.16python3.6.____cpython.zst.log](https://github.com/conda-forge/pytorch-cpu-feedstock/files/5744163/linux_64_cuda_compiler_version9.2numpy1.16python3.6.____cpython.zst.log)
* [linux_64_cuda_compiler_version9.2numpy1.16python3.7.____cpython.zst.log](https://github.com/conda-forge/pytorch-cpu-feedstock/files/5744159/linux_64_cuda_compiler_version9.2numpy1.16python3.7.____cpython.zst.log)
* [linux_64_cuda_compiler_version9.2numpy1.16python3.8.____cpython.zst.log](https://github.com/conda-forge/pytorch-cpu-feedstock/files/5744152/linux_64_cuda_compiler_version9.2numpy1.16python3.8.____cpython.zst.log)
* [linux_64_cuda_compiler_version9.2numpy1.19python3.9.____cpython.zst.log](https://github.com/conda-forge/pytorch-cpu-feedstock/files/5744155/linux_64_cuda_compiler_version9.2numpy1.19python3.9.____cpython.zst.log)
* [linux_64_cuda_compiler_version10.0numpy1.16python3.6.____cpython.zst.log](https://github.com/conda-forge/pytorch-cpu-feedstock/files/5744161/linux_64_cuda_compiler_version10.0numpy1.16python3.6.____cpython.zst.log)
* [linux_64_cuda_compiler_version10.0numpy1.16python3.7.____cpython.zst.log](https://github.com/conda-forge/pytorch-cpu-feedstock/files/5744157/linux_64_cuda_compiler_version10.0numpy1.16python3.7.____cpython.zst.log)
* [linux_64_cuda_compiler_version10.0numpy1.16python3.8.____cpython.zst.log](https://github.com/conda-forge/pytorch-cpu-feedstock/files/5744151/linux_64_cuda_compiler_version10.0numpy1.16python3.8.____cpython.zst.log)
* [linux_64_cuda_compiler_version10.0numpy1.19python3.9.____cpython.zst.log](https://github.com/conda-forge/pytorch-cpu-feedstock/files/5744153/linux_64_cuda_compiler_version10.0numpy1.19python3.9.____cpython.zst.log)
* [linux_64_cuda_compiler_version10.1numpy1.16python3.6.____cpython.zst.log](https://github.com/conda-forge/pytorch-cpu-feedstock/files/5744150/linux_64_cuda_compiler_version10.1numpy1.16python3.6.____cpython.zst.log)
* [linux_64_cuda_compiler_version10.1numpy1.16python3.7.____cpython.zst.log](https://github.com/conda-forge/pytorch-cpu-feedstock/files/5744160/linux_64_cuda_compiler_version10.1numpy1.16python3.7.____cpython.zst.log)
* [linux_64_cuda_compiler_version10.1numpy1.16python3.8.____cpython.zst.log](https://github.com/conda-forge/pytorch-cpu-feedstock/files/5744156/linux_64_cuda_compiler_version10.1numpy1.16python3.8.____cpython.zst.log)
* [linux_64_cuda_compiler_version10.1numpy1.19python3.9.____cpython.zst.log](https://github.com/conda-forge/pytorch-cpu-feedstock/files/5744149/linux_64_cuda_compiler_version10.1numpy1.19python3.9.____cpython.zst.log)
* [linux_64_cuda_compiler_version10.2numpy1.16python3.6.____cpython.zst.log](https://github.com/conda-forge/pytorch-cpu-feedstock/files/5744162/linux_64_cuda_compiler_version10.2numpy1.16python3.6.____cpython.zst.log)
* [linux_64_cuda_compiler_version10.2numpy1.16python3.7.____cpython.zst.log](https://github.com/conda-forge/pytorch-cpu-feedstock/files/5744158/linux_64_cuda_compiler_version10.2numpy1.16python3.7.____cpython.zst.log)
* [linux_64_cuda_compiler_version10.2numpy1.16python3.8.____cpython.zst.log](https://github.com/conda-forge/pytorch-cpu-feedstock/files/5744148/linux_64_cuda_compiler_version10.2numpy1.16python3.8.____cpython.zst.log)
* [linux_64_cuda_compiler_version10.2numpy1.19python3.9.____cpython.zst.log](https://github.com/conda-forge/pytorch-cpu-feedstock/files/5744154/linux_64_cuda_compiler_version10.2numpy1.19python3.9.____cpython.zst.log)

**Comment by isuruf** [comment]
Thanks @chrisburr

**Comment by hmaarrfk** [comment]
Super!

**Pull request merged**
