### PR TITLE
Rebuild cuda118, cuda1120, and protobuf

### PR DESCRIPTION
**Pull request by RaulPPelaez**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Continuing #191 I added the necessary CUDA arch flags to build_pytorch.sh.

### CODE REVIEW

**Comment by RaulPPelaez** [comment]
@conda-forge-admin, please rerender

**Comment by RaulPPelaez** [comment]
These ones were running, but they were timed out:
```shell
  [5220/5707] Building CUDA object caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/ForeachUnaryOp.cu.o
  [5221/5707] Building CUDA object caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/IGammaKernel.cu.o
  [5222/5707] Building CUDA object caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/Im2Col.cu.o
  [5223/5707] Building CUDA object caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/GridSampler.cu.o
##[error]The operation was canceled.
Finishing: Run docker build
```
They just take really really long it seems. Not sure what can be done in order to reduce this time.
Any advice here @jakirkham?

**Comment by hmaarrfk** [comment]
I've always been building cuda locally. the fat binaries are just really slow to compile.

**Comment by hmaarrfk** [comment]
I can try to start building this locally and see where it goes. I am not overly enthusiastic to build out 3 cuda versions (11.2, 11.8, and 12.0).....

**Comment by RaulPPelaez** [comment]
> I've always been building cuda locally. the fat binaries are just really slow to compile.

I did not know that was an option hehe. I know how to build locally, but I assume the results are not something I can somehow upload here myself?

> I can try to start building this locally and see where it goes. I am not overly enthusiastic to build out 3 cuda versions (11.2, 11.8, and 12.0).....

I understand it is a hassle, but torch is a really big package and I believe it is worth to provide these options. It is true though that minor CUDA versions are supposed to be compatible amongst them, but even in  that case I would assume CUDA 11.8 provides some kind of performance enhancement with respect 11.2.
At least CUDA 12 should be an option to reduce the chances of dependency hell.

**Comment by hmaarrfk** [comment]
See https://github.com/conda-forge/cfep/blob/main/cfep-03.md


is 11.8 useful if we provide 12.0? 

It just really is ALOT of package data (storage) and compilation time.

**Comment by RaulPPelaez** [comment]
Current 11.2 builds have in the order of 100k downloads since 6 months ago. People are using it.
One could argue that now that pytorch 2.1.0 is out it is a weird use case to start depending on torch 2.0+CUDA!=11.2. We could decide to just leave 2.0.0 without CUDA 11.8 and 12 builds if it is a burden. After all people had have no possibility to depend on them.

Thing is we are having a hard time compiling 2.1.0 -.- This is why I believe it is worth giving people the chance to have torch2.0@CUDA12.

**Comment by jakirkham** [comment]
CUDA 11.8 supports the same hardware as 11.2 (assuming the driver is reasonably up-to-date). So it may make sense to drop 11.2 and keep 11.8

With CUDA 12.0, support for [Kepler is dropped]( https://docs.nvidia.com/cuda/archive/12.0.0/cuda-toolkit-release-notes/index.html#deprecated-features ). Not sure of exact usage metrics atm, but this may be a consideration

**Comment by hmaarrfk** [comment]
can users with cuda=11.2 install the 11.8 packages?

**Comment by jakirkham** [comment]
They may need to install the newer CTK, but that should be doable. Also they may need to update their driver. Though they should be able to use the same hardware, which may be the more important bit

With CUDA 12.0, the CTK is fully contained within Conda packages, which includes the compiler & headers. So the driver is the only thing outside Conda needing updating

**Comment by hmaarrfk** [comment]
https://docs.nvidia.com/deploy/cuda-compatibility/

Not sure why i really care. the biggest barrier is me starting my script.

**Comment by hmaarrfk** [comment]
@RaulPPelaez were you able to get Cuda 12.0 to also compile? if so do you want to add it to this merge request and I can trigger a rebuild.

**Comment by jakirkham** [comment]
> the biggest barrier is me starting my script.

Yeah we need to figure out a way to automate builds

**Comment by RaulPPelaez** [comment]
> @RaulPPelaez were you able to get Cuda 12.0 to also compile? if so do you want to add it to this merge request and I can trigger a rebuild.

Those also timed out, the PR for CUDA 12 https://github.com/conda-forge/pytorch-cpu-feedstock/pull/193 should also be compatible with CUDA 11.8.
Not sure how the pipeline works in this case. I merged #193 here, not sure if that is enough.

**Comment by jakirkham** [comment]
Think what Mark is asking is if you have tried building locally (and if so whether those builds completed)

Guessing most build errors occur early (like those seen previously: https://github.com/conda-forge/pytorch-cpu-feedstock/pull/193#issuecomment-1779286947 )

Though there are some errors that might not show up until the linking stage

Another question would be whether we see issues during testing (not sure what testing is done for the CUDA packages)

**Comment by hmaarrfk** [comment]
I have the following done canaries completed.

```
conda-forge-build-done-linux_64_blas_implgenericc_compiler_version11cuda_compilernvcccuda_compiler_version11.8cxx_compiler_version11numpy1.22python3.10.____cpython
conda-forge-build-done-linux_64_blas_implgenericc_compiler_version11cuda_compilernvcccuda_compiler_version11.8cxx_compiler_version11numpy1.22python3.8.____cpython
conda-forge-build-done-linux_64_blas_implgenericc_compiler_version11cuda_compilernvcccuda_compiler_version11.8cxx_compiler_version11numpy1.22python3.9.____cpython
conda-forge-build-done-linux_64_blas_implgenericc_compiler_version11cuda_compilernvcccuda_compiler_version11.8cxx_compiler_version11numpy1.23python3.11.____cpython
conda-forge-build-done-linux_64_blas_implmklc_compiler_version10cuda_compilernvcccuda_compiler_version11.2cxx_compiler_version10numpy1.22python3.10.____cpython
conda-forge-build-done-linux_64_blas_implmklc_compiler_version10cuda_compilernvcccuda_compiler_version11.2cxx_compiler_version10numpy1.23python3.11.____cpython
conda-forge-build-done-linux_64_blas_implmklc_compiler_version12cuda_compilercuda-nvcccuda_compiler_version12.0cxx_compiler_version12numpy1.22python3.8.____cpython
```

That said, i'm wondering if for the sake of conda-forge's storage quote, if i shoul dcancel (now that I have one build of 11.2, 11.8 and 12.0 complete) cancel these builds and work to integrate https://github.com/conda-forge/pytorch-cpu-feedstock/pull/197

**Comment by jakirkham** [comment]
@h-vetinari do you have a sense of how #197 should factor in here?

**Comment by h-vetinari** [comment]
> @h-vetinari do you have a sense of how #197 should factor in here?

If it can be integrated, all the better! If not, it's not the end of the world, but should then go into the next build. With pytorch, the recent protobuf bumps seemed to go pretty smoothly though (from what I can tell, esp. compared to TF).

**Comment by hmaarrfk** [comment]
they work. builds take a full day. restarting them now with abseil migration

**Comment by hmaarrfk** [comment]
log files

[log_files.zip](https://github.com/conda-forge/pytorch-cpu-feedstock/files/13257183/log_files.zip)

**Comment by Tobias-Fischer** [comment]
Hi @hmaarrfk - have these builds actually been uploaded to the conda-forge channel? I might be blind seeing only the cpu builds.

**Comment by Tobias-Fischer** [comment]
Background: I’m trying to figure out why https://github.com/conda-forge/pytorch_scatter-feedstock/pull/55 can’t find solve the environment

**Comment by hmaarrfk** [comment]
lol, maybe not.... I might just upload the next ones if that is ok?

**Comment by jakirkham** [comment]
Meaning with the changes from PR ( https://github.com/conda-forge/pytorch-cpu-feedstock/pull/199 )?

**Comment by hmaarrfk** [comment]
yes.

I mean, i'm really not excited about them either, but they are complete....

**Comment by jakirkham** [comment]
Yeah that seems better from a user standpoint (recent version + Python 3.12)

**Comment by hmaarrfk** [comment]
Ohhhh. i found the builds:

https://anaconda.org/mark.harfouche/pytorch/files
https://anaconda.org/mark.harfouche/pytorch-gpu/files

**Comment by jakirkham** [comment]
Thanks Mark! 🙏

**Pull request merged**
