### PR TITLE
Bump to PyTorch 2.0.0

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Fixes #151

**Comment by Tobias-Fischer** [comment]
Still struggling with some issues.

1) For the non-cuda build on linux-64, at least locally I was running into issues where the run dependencies of the pytorch package are not pulled in by the pytorch-cpu package (which is really weird) and leads for the build to fail as `sympy` cannot be found when `import torch`.

2) Locally the cuda build fails with
```
conda.CondaMultiError: The package for cudnn located at /home/conda/feedstock_root/build_artifacts/pkg_cache/cudnn-8.4.1.50-hed8a83a_0
appears to be corrupted. The path 'bin/.cudnn-post-link.sh'
specified in the package manifest cannot be found.

The package for cudnn located at /home/conda/feedstock_root/build_artifacts/pkg_cache/cudnn-8.4.1.50-hed8a83a_0
appears to be corrupted. The path 'include/cudnn.h'
specified in the package manifest cannot be found.
```

3) Have not tested the osx builds.


Let's see what happens in CI.

**Comment by Tobias-Fischer** [comment]
It seems like this is working quite well :)

Unfortunately linux-aarch64 errors with:
```
ImportError: /home/conda/feedstock_root/build_artifacts/pytorch-recipe_1680469918528/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameEv
```

Any ideas where this issue might be from @conda-forge/pytorch-cpu @conda-forge/libprotobuf @conda-forge/protobuf? It seems like it could be related to the gcc version (https://github.com/NVIDIA-AI-IOT/torch2trt/issues/53)? I can only find this issue on conda-forge but it does not seem to apply here (mixing defaults and conda-forge channels): https://github.com/conda-forge/paraview-feedstock/issues/23

Several issues hint to towards issues with onnx/caffe2.

**Comment by hmaarrfk** [comment]
my guess is that somebody is re-exporting the symbols publicly. It may be the vendored onnx?

**Comment by hmaarrfk** [comment]
Maybe related to: https://github.com/pytorch/pytorch/blob/5d62d1255778b53ece16c79fd842cd42eca31f93/CMakeLists.txt#L175

**Comment by Tobias-Fischer** [comment]
Looks like this is now ready for review. Could someone else please test a cuda build locally?

**Comment by Tobias-Fischer** [comment]
Thanks @hmaarrfk!

We can test the gpu builds with
```
>>> import torch

>>> torch.cuda.is_available()
True

>>> torch.cuda.device_count()
1
```

**Comment by hmaarrfk** [comment]
```
>>> import torch
>>> torch.cuda.is_available()
True
>>> torch.cuda.device_count()
1
>>> print(torch.__version__)
2.0.0.post200
```

is the `post` expected?

**Comment by hmaarrfk** [comment]
Builds starting to upload https://anaconda.org/mark.harfouche/pytorch/files if people want a more thorough test.

**Comment by Tobias-Fischer** [comment]
There are a few instances of `post200` when searching on the PyTorch repo: https://github.com/search?q=repo%3Apytorch%2Fpytorch+post200&type=issues

Not sure what it refers to

**Comment by hmaarrfk** [comment]
Of course, pytorch needs to have a custom version numbering system ^_^

https://github.com/pytorch/pytorch/blob/73b06a0268bb89c09a86f16fa0f72818baa4b250/tools/generate_torch_version.py#L51

The use the CONDA_BUILD_NUMBER and add it to the version number.

I can't fully trace it, but it seems to be related to the build number. 

Lets maybe flag this as an issue, but I don't want to patch too much at this stage.

**Comment by Tobias-Fischer** [comment]
I don't think it's a big deal, is it? If you really wanted to, we could change https://github.com/Tobias-Fischer/pytorch-cpu-feedstock/blob/5f00d8033d7cc23eb9831c74dc038fe3e4047562/recipe/build_pytorch.sh#LL56 to 0 instead.

**Comment by hmaarrfk** [comment]
I think it is ok as is.
Ah thnk you. i searched pytorch's repo for that statement but forgot that maybe we just set it...

Eventually, i think somebody's version check will be broken but we can deal with it later.

**Comment by Tobias-Fischer** [comment]
So far no one has complained, and we've had the same situation in past conda-forge builds:
```
>>> torch.__version__
'1.13.0.post200'
```

**Comment by hmaarrfk** [comment]
Yeah. I agree. I think it's fine.

Just waiting for the builds at this stage.

**Comment by h-vetinari** [comment]
I thought that 2.0 needed Triton as a backend, or is that optional...?

**Comment by hmaarrfk** [comment]
hm, sorry i forgot to test for triton, is there a "test" you would like be to try on a GPU?

**Comment by hmaarrfk** [comment]
linux compiling just takes "time" but it is easy to start, so if somebody wants to add triton support, i can rebuild linux.

**Comment by Tobias-Fischer** [comment]
- I am a bit confused what is depending on what. As far as I can see, pytorch depends on torchtriton, which in turn seems to depend on pytorch. 
- Is there any difference between torchtriton and triton?
- We already package an old version of triton in conda-forge and have a PR open for version 2.0.0 (https://github.com/conda-forge/triton-feedstock/pull/2). Would this 2.0.0 version be suitable as dependency for here?

**Comment by Tobias-Fischer** [comment]
Another issue seems to be that I can't install a recent version of torchvision and pytorch=2 side-by-side; I manage to kill mamba ;)

```
> mamba create -n pytorch21 pytorch=2 torchvision=0.14
python: /home/conda/feedstock_root/build_artifacts/mamba-split_1680002410624/work/libmamba/src/core/satisfiability_error.cpp:1767: mamba::{anonymous}::TreeExplainer::node_t mamba::{anonymous}::TreeExplainer::concat_nodes(const std::vector<long unsigned int>&): Assertion `std::all_of( ids.begin(), ids.end(), [&](auto id) { return m_pbs.graph().node(ids.front()).index() == m_pbs.graph().node(id).index(); } )' failed.
```

If I don't specify the torchvision version, it pulls in a very old torchvision which is definitely not compatible ..

**Comment by hmaarrfk** [comment]
pytorch run exports itself, so torchvision has to be rebuilt.

**Pull request merged**
