### PR TITLE
Feat/windows ci runner

### PR DESCRIPTION
**Pull request by wolfv**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by aktech** [comment]
Thanks for creating this I was just about to work on creating this one.

**Comment by wolfv** [comment]
Sure thing! Rebasing was actually a bit painful :) 

Any idea why cirun is failing? Did I use the wrong label?

**Comment by aktech** [comment]
The error is: [No runners configuration found after labels filtering](https://github.com/conda-forge/pytorch-cpu-feedstock/pull/242/checks?check_run_id=26509279621)

The workflow is requesting labels: `x64`, `cirun-azure-windows-2xlarge`, `windows`. The `x64` is missing from here: https://github.com/conda-forge/.cirun/blob/b2aeabf22170179a4eb17f3f3c1e4eb45580e142/.cirun.global.yml#L127 I've just created a PR now: https://github.com/conda-forge/.cirun/pull/15

**Comment by wolfv** [comment]
Great. Should I push an empty commit to trigger?

**Comment by aktech** [comment]
Yes, that should work.

**Comment by wolfv** [comment]
Alright, I triggered!

**Comment by wolfv** [comment]
still not starting, any ideas @aktech ? :)

**Comment by aktech** [comment]
Yep, investigating

**Comment by hmaarrfk** [comment]
sorry again for the conflicts.

**Comment by baszalmstra** [comment]
I incorporated all you changes in #231 I think we can close this.

**Pull request closed without merging**
